In [0]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [3]:
print(tf.__version__)
print(keras.__version__)

2.2.0-rc3
2.3.0-tf


In [0]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [0]:
# Example training data, of dtype `string`.
training_data = np.array([["This is the 1st sample."],
                          ["And here's the 2nd sample."],
                          ["Finally, this is the last example bla bla bla"]])

In [0]:
# Create a TextVectorization layer instance. It can be configured to either
# return integer token indices, or a dense token representation (e.g. multi-hot
# or TF-IDF). The text standardization and text splitting algorithms are fully
# configurable.
vectorizer = TextVectorization(output_mode='int')

In [0]:
vectorizer.adapt(training_data)

In [19]:
# After calling adapt, the layer is able to encode any n-gram it has seen before
# in the `adapt()` data. Unknown n-grams are encoded via an "out-of-vocabulary"
# token.
integer_data = vectorizer(training_data)
print(integer_data)
print(integer_data.shape)
print(integer_data.dtype)

tf.Tensor(
[[ 3  5  2 12  4  0  0  0  0]
 [10  7  2 11  4  0  0  0  0]
 [ 8  3  5  2  6  9  1  1  1]], shape=(3, 9), dtype=int64)
(3, 9)
<dtype: 'int64'>
